version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reliance_stock_prediction
    ports:
      - "8501:8501"
    volumes:
      - .:/home/ak/lstm_reliance_stock
    environment:
      - PYTHONUNBUFFERED=1
    command: python app.py